# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'TinderClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TinderClone
	pod 'FirebaseFirestore'
	pod 'FirebaseAuth'
	pod 'FirebaseStorage'
	pod 'SDWebImage', '~> 5.0'
	pod 'JGProgressHUD', '~> 2.0.3'
end
